require "seyza.options"
require "seyza.keymaps"
require "seyza.plugins"
require "seyza.comment"
require "seyza.autocommands"
require "seyza.colorscheme"
require "seyza.cmp"
require "seyza.telescope"
require "seyza.treesitter"
require "seyza.autopairs"
require "seyza.gitsigns"
require "seyza.nvim-tree"
require "seyza.lualine"
require "seyza.toggleterm"
require "seyza.project"
require "seyza.impatient"
require "seyza.indentline"
require "seyza.alpha"
-- require "seyza.zen-mode"
require "seyza.illuminate"
-- require "seyza.dap"
require "seyza.nvim-webdev-icons"
require "seyza.lsp"
require "seyza.bufferline"
